name: Build, Run & Deploy

on:
  schedule:
    - cron: "0 23,17,11,5 * * *" # Runs at 9am (daylight savings or 10 am non-daylight savings).
  workflow_dispatch: 
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    container: bsefton/estuary_reports_ubuntu_python:latest
    steps:
    - name: Python Clone & Run
      uses: actions/checkout@v2
    - name: Make env
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DW_KEY: ${{ secrets.DW_KEY }}
        envkey_CLYDE_ORG_KEY: ${{ secrets.CLYDE_ORG_KEY }}
    - run: |
        pwd
        ls -a
        cp .env src/.env
        cd src
        python3 main.py
    - name: Upload PDF Report
      uses: actions/upload-artifact@v2
      with:
        name: report.pdf 
        path: src/output/clyde/report/report.pdf
